---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  namespace: default
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  nodejs:
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  namespace: default
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  dotnet:
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-instrumentation
  namespace: default
spec:
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
  go: