apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: 'dotnet-instrumentation'
        sidecar.opentelemetry.io/inject: 'sidecar'
