apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: 'nodejs-instrumentation'
        sidecar.opentelemetry.io/inject: 'sidecar'
