version: '3'
services:

  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  votes:
    build: .
    hostname: votes
    container_name: votes
    restart: always
    depends_on:
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis:6379
