name: votes

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "votes/**" ]

jobs:
  votes:
    runs-on: ubuntu-latest
    steps:
    - name: git clone
      uses: actions/checkout@v3
    - name: docker login
      run: docker login --username mac2000 --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: docker build
      run: docker build -f votes/Dockerfile -t mac2000/bookstore-votes votes
    - name: docker push
      run: docker push mac2000/bookstore-votes
